### ISSUE TITLE
Get around Gatekeeper on Mac

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#104]
Currently on macOS one needs to hold control and then right click on the icon and then click on open to get XUD Explorer running. https://developer.apple.com/developer-id/ should solve this.

**Comment by kilrau** [comment]
Let's find out if wasabi or bisq found a amsarter way to get around that.

**Comment by peartobear** [comment]
Related signing electron app: https://www.electronjs.org/docs/tutorial/code-signing I think we can skip this short term and come back when there's substantial mac users demanding it.

**Comment by kilrau** [comment]
> Let's first find out if wasabi or bisq found a smarter way to get around that.

Did you find out? @peartobear

**Comment by kilrau** [comment]
closing here as duplicate of https://github.com/ExchangeUnion/xud-ui/issues/73
