### ISSUE TITLE
JavaScript error in main process when xud-docker not running

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#105]
Reported by @peartobear :+1: 

> I have no docker open, so it was showing a loading Spinner, when I closed the explorer, this error popped up.

![image](https://user-images.githubusercontent.com/19181985/98810626-cacdc080-241f-11eb-84df-dcb5a55eb4a7.png)

**Comment by kilrau** [comment]
Should be solved by [binary launcher](https://github.com/ExchangeUnion/xud-docker/issues/788).

**Comment by erkarl** [comment]
>  be solved by [binary launcher](https://github.com/ExchangeUnion/xud-docker/issues/788).

Yes.

**Comment by kilrau** [comment]
Oh I see market as closed by https://github.com/ExchangeUnion/xud-ui/pull/120
