### ISSUE TITLE
Tradehistory: default sorting should be time **descending**

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#107]
Default sorting should be by time descending, so that the newest trades are on top.

![image](https://user-images.githubusercontent.com/19181985/98928042-93bbe580-24d9-11eb-8078-71e93887dc66.png)

**Comment by krrprr** [comment]
@kilrau I don't seem to be able to reproduce this - the default sorting by time is always descending for me. Can you provide in which circumstances it appears ascending by default?

**Comment by kilrau** [comment]
Actually looking closer at it, it looks like sorting by time is just buggy:

Sorted by time ascending:
![image](https://user-images.githubusercontent.com/19181985/99240826-54ed9e80-27fd-11eb-85ee-6bba306d6c65.png)

Sorted by time descending:
![image](https://user-images.githubusercontent.com/19181985/99240892-69ca3200-27fd-11eb-8360-ed861a267808.png)

**Comment by krrprr** [comment]
Got it @kilrau, thanks for the hint!
It compares the string values, not dates.

**Comment by kilrau** [comment]
That explains it :)
