### ISSUE TITLE
Landing page for macOS+Linux

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#112]
Currently only available on Windows.
- Once the binary launcher is available, macOS+Linux should have a landing page (Create/Start, Connect)
- Once this is done, `disconnect` should always go back to landing page and behavior of disconnect/back button should be the same on all platforms

**Comment by kilrau** [comment]
Ignoring installation of docker, the only dependency to make a landing page happen on macOS/linux is the binary launcher, correct @erkarl ?

**Comment by erkarl** [comment]
I believe so. P1 is still full focus on Windows support first, though.
