### ISSUE TITLE
incorrect xud address setting leads to empty screen

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-ui#117]
Steps:
1. Open Connection page
2. Enter invalid xud address - ( change port to unavailable one for example) 

Actual result:
Empty grey page
Video: https://gofile.io/d/3RR9RZ

Expected result:
Retry button + text err

**Comment by krrprr** [comment]
Thanks for discovering this @raladev !

We should add an error handling in case the URL cannot be parsed (the port is out of range or the URL is somehow malformed).

**Comment by rsercano** [comment]
As soon as https://github.com/ExchangeUnion/xud-ui/pull/115 is merged, I would like to check this too
