### ISSUE TITLE
Boltz Deposit/Withdrawal follow-ups

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#118]
- [ ] remove QR button from withdrawal
- [ ] convert sats / lites to BTC/LTC, make it globally accessible so that we can have a denomination switcher later, e.g. BTC-> sats
- [ ] display max limit -> min(boltz max limit, our total channel balance)
- [ ] if total channelbalance is below boltz min limit -> insufficient funds error (min is X, you have Y)
- [ ] if total channelbalance lower than entered amount -> insufficent funds error (you entered X, you have Y)
- [ ] slightly increase of original wallet overview box, reduce height of withdrawal / deposit box views, by moving show QR into address box, moving bolt & miner fee into one line and removing "check status button" (see points below)-> goal: card size stays the same throughout all flows
- [ ] boltz withdrawal confirmation: `To check status run `boltzcli BTC swapinfo ID` in the console tab.
- [ ] boltz deposit: `To check status run `boltzcli BTC swapinfo ID` in the console tab. Currently need 
- [ ] get full map of boltz errors, define clean error message each
- [ ] You are using Boltz (i)->https://boltz.exchange/ as swap service. Fee: X (1%), Miner Fee: Y

**Comment by krrprr** [comment]
> You are using Boltz (i)->https://boltz.exchange/ as swap service.

Had to include it all into a tooltip as it would have otherwise taken more than one row.

> if total channelbalance is below boltz min limit -> insufficient funds error (min is X, you have Y)
> if total channelbalance lower than entered amount -> insufficent funds error (you entered X, you have Y)

The first error also covers the second case imho. Currently implemented it so that error message does therefore not change as user types an amount.
