### ISSUE TITLE
App icon not shown on Ubuntu when opened via the launcher

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#130]
When the app is added to the Applications (via AppImageLauncher) and opened via the launcher after the first run, a default icon is displayed in the dock instead of the xud-ui app icon.

**Comment by kilrau** [comment]
> via AppImageLauncher

That's the one: https://github.com/TheAssassin/AppImageLauncher

Could you reproduce? @krrprr

**Comment by krrprr** [comment]
> > via AppImageLauncher
> 
> That's the one: https://github.com/TheAssassin/AppImageLauncher
> 
> Could you reproduce? @krrprr

yes, with https://github.com/TheAssassin/AppImageLauncher it was reproducible.
