### ISSUE TITLE
Remove xud-docker env fully during removal proccess

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-ui#137]
As a user i want to remove any mentions about the app when use `add/reemove program` windows functionality.

for now we do not remove all data. To be honest i even dont know what data we remove during such process exept of windows icon, because all data that i know still exists on hard drive.

What should be removed?
- C:\Users\Ro-ma\AppData\Roaming\xud-ui folder
- C:\Users\Ro-ma\AppData\Local\XudDocker folder
- C:\Users\Ro-ma\AppData\Local\xud-ui-updater folder
- All containers and **images** that connected with xud-docker
- if docker was installed during xud installation, would be good to remove it too (we can add checkbox for that to removal window).

@krrprr is there any other data that exists on windows hard drive?

**Comment by kilrau** [comment]
Good point, we should take care of this in the Windows `uninstall` process. Not super critical though -> P2.
