### ISSUE TITLE
Black screen when installing new XUD UI

### ISSUE THREAD

**Issue by JoPark20** [ExchangeUnion/xud-ui#139]
I tried to do a fresh set-up with version 1.20. 
At first it looked okay:
![Screenshot (99)](https://user-images.githubusercontent.com/43677783/102460637-944f1b00-4047-11eb-8dfb-02337de6d2ae.png)

Got a warning then:
![Screenshot (102)_LI](https://user-images.githubusercontent.com/43677783/102460655-9add9280-4047-11eb-9e57-4737b7ef516f.jpg)

Resulting into a forever black screen:
![Screenshot (103)](https://user-images.githubusercontent.com/43677783/102460675-a29d3700-4047-11eb-95de-1623da13716e.png)

The pop-up lead me to https://docs.docker.com/docker-for-windows/wsl/#develop-with-docker-and-wsl-2 => i am lost here as a tech newbie.

**Comment by kilrau** [comment]
Many thanks for running this and sorry that you ran into this bug. I'd be lost too and honestly now idea what happened there since none of us saw this so far :/ 

Docker Desktop was running and didn't report any errors, correct?

Could you give us:
- your Windows build version number (screenshot is fine)
- docker desktop and engine version number (screenshot is fine)
- log file (should be located in `C:\Users\<YourUsername>\AppData\Local\XudDocker`)

**Comment by krrprr** [comment]
Thanks for reporting this!
Can you also provide
- the log files that are located in `C:\Users\<YourUsername>\AppData\Roaming\xud-ui\logs`
- console output: after opening the app, type `ctrl + shift + i`, then proceed with creating/starting the environment and send either a screenshot or copied text from the console once the screen has turned black.

**Comment by JoPark20** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/43677783/102472601-bbf9af80-4056-11eb-821e-1d277ee139ed.png)


![Screenshot (107)](https://user-images.githubusercontent.com/43677783/102472497-9f5d7780-4056-11eb-9ad9-09711d96eb9f.png)

Logs:
![Screenshot (106)_LI](https://user-images.githubusercontent.com/43677783/102472170-5279a100-4056-11eb-9062-50f65f9e95b6.jpg) :

[renderer.log](https://github.com/ExchangeUnion/xud-ui/files/5708423/renderer.log)

C:\Users\<YourUsername>\AppData\Local\XudDocker => is empty, only a mainnet.log is created ( also empty)

**Comment by JoPark20** [comment]
![Screenshot (113)](https://user-images.githubusercontent.com/43677783/102473147-696cc300-4057-11eb-9092-4f3b9096b862.png)
![Screenshot (114)](https://user-images.githubusercontent.com/43677783/102473151-6a9df000-4057-11eb-8fc7-995eb0c639d8.png)

**Comment by krrprr** [comment]
Thank you @JoPark20 ! The screenshot you provided gave enough information.
Please try the following as a workaround:
- shutdown xud-ui
- open Docker's main screen. You should see a list of running containers. Stop and remove each of them.
- reopen xud-ui and see if it works now.

**Comment by JoPark20** [comment]
Nice - it worked now and is syncing now!

Maybe this was the issue (xud ui not shutting down after closing app)?:
![Screenshot (118)](https://user-images.githubusercontent.com/43677783/102474925-8a361800-4059-11eb-826a-6e6247a26482.png)

I must admit i might have clicked xud setup.exe too often, maybe this triggered the error.

Docker screenshot, but i guess not necessary:
![Screenshot (117)](https://user-images.githubusercontent.com/43677783/102474927-8aceae80-4059-11eb-81a5-e3e3914c573b.png)

**Comment by JoPark20** [comment]
Update in 1 minute:

**Comment by kilrau** [comment]
> Update when closing app, this pops up:
> ![Screenshot (120)](https://user-images.githubusercontent.com/43677783/102475527-41329380-405a-11eb-8892-a5b6925e411a.png)

Yes, that's a change we did to prevent users accidentally shutting down the environment. The environment keeps fully running now when the user clicks [x]. To fully shutdown, right-click -> shutdown in the tray.

**Comment by kilrau** [comment]
> now i cant open the app (but it still shown as open and running at the bottom ) & at task manager several xud ui apps are shwon running:
> ![Screenshot (124)](https://user-images.githubusercontent.com/43677783/102475734-8c4ca680-405a-11eb-9baa-968620e5a834.png)

That doesn't look too good. I remember we prevented multiple xud ui instances from starting at the same time? @krrprr

**Comment by krrprr** [comment]
> Update when closing app, this pops up:
> ![Screenshot (120)](https://user-images.githubusercontent.com/43677783/102475527-41329380-405a-11eb-8892-a5b6925e411a.png)

When closing the window, the app still remains running and can be shut down from the xud tray icon's shutdown (the icon is currently probably hidden under the up arrow in your dock).
The xud's ` setup.exe` should only be clicked once when installing the app. Please close all the xud-ui tasks from task manager and reopen the app via shortcut.

**Comment by krrprr** [comment]
> > now i cant open the app (but it still shown as open and running at the bottom ) & at task manager several xud ui apps are shwon running:
> > ![Screenshot (124)](https://user-images.githubusercontent.com/43677783/102475734-8c4ca680-405a-11eb-9baa-968620e5a834.png)
> 
> That doesn't look too good. I remember we prevented multiple xud ui instances from starting at the same time? @krrprr

Seems rather the consequence of

> I must admit i might have clicked xud setup.exe too often, maybe this triggered the error.


as this does not create another instance of the same app but a different app.

**Comment by JoPark20** [comment]
> > Update when closing app, this pops up:
> > ![Screenshot (120)](https://user-images.githubusercontent.com/43677783/102475527-41329380-405a-11eb-8892-a5b6925e411a.png)
> 
> Yes, that's a change we did to prevent users accidentally shutting down the environment. The environment keeps fully running now when the user clicks [x]. To fully shutdown, right-click -> shutdown in the tray.
do you mean i should click this? this doesnt change anything. will close all running tasks and start again. update in 2-3 min
![Screenshot (126)_LI](https://user-images.githubusercontent.com/43677783/102476307-3d534100-405b-11eb-8a66-0d713503caf1.jpg)

**Comment by kilrau** [comment]
> > I must admit i might have clicked xud setup.exe too often, maybe this triggered the error.
> as this does not create another instance of the same app but a different app.

We still should try to prevent this.

**Comment by JoPark20** [comment]
I stopped now all xud ui tasks running at task manager. 
![Screenshot (129)](https://user-images.githubusercontent.com/43677783/102477250-67593300-405c-11eb-9041-b705d74d2c2a.png)

Stopped an removed the running mainnet at docker.
opened my xud shortcut:
![Screenshot (131)_LI](https://user-images.githubusercontent.com/43677783/102477311-7a6c0300-405c-11eb-9fa0-f9b99108a8bf.jpg)

and now already three xud ui tasks are running:
![Screenshot (130)](https://user-images.githubusercontent.com/43677783/102477350-89eb4c00-405c-11eb-9ae6-9b9231e8fa7c.png)

**Comment by krrprr** [comment]
![Screenshot from 2020-12-17 12-37-35](https://user-images.githubusercontent.com/24500376/102477338-e7839680-4064-11eb-8bba-4982393663c6.png)

Really sorry that it's not so obvious and the icon gets hidden under the up arrow in Windows.

**Comment by JoPark20** [comment]
> ![Screenshot from 2020-12-17 12-37-35](https://user-images.githubusercontent.com/24500376/102477338-e7839680-4064-11eb-8bba-4982393663c6.png)
> 
> Really sorry that it's not so obvious and the icon gets hidden under the up arrow in Windows.

okay this work - this stopped everything (though three and then two XUD symbols were visible **before** i stopped it)

**Comment by krrprr** [comment]
> and now already three xud ui tasks are running again

This is normal because the app has several processes running (e.g main, renderer), and each of them gets its own task in task manager.

**Comment by JoPark20** [comment]
Update: 
Tried to stop and delete every XUD related folder / data and do a very fresh complete clean installation. 
This time it worked smoothly. So i guess i didnt delete eg the xud-docker folder the last time, which then caused all the errors. Will test closing + restarting then again. Sorry for the confsuion, i was actually sure i deleted everything.
But now i have one question: why doesnt get the environment shutdown when closing the app?
I know i am no experienced user, but at the moment it is quite difficult to shut it down completely (if you dont know it yet)

**Comment by reliveyy** [comment]
![image](https://user-images.githubusercontent.com/4723958/102504374-b5e9ea00-40bb-11eb-988b-e544ed570e86.png)

@kilrau @krrprr For me it's just in a process group

**Comment by reliveyy** [comment]
```
[2020-12-17 03:02:49.593] [error] failed to stop containers. Error: Command failed: C:\Users\yy\AppData\Local\Programs\xud-ui\resources\xud-launcher.exe down
[8544] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

**Comment by reliveyy** [comment]
```
[2020-12-07 15:01:38.860] [error] failed to stop containers. Error: Command failed: E:\Work\ExchangeUnion\xud-ui\public\assets\xud-launcher.exe -n mainnet down
Error: unknown shorthand flag: 'n' in -n
Usage:
  xud-launcher down [flags]

Flags:
  -h, --help   help for down

Global Flags:
      --mainnet-dir string   Mainnet environment folder (default "C:\\Users\\yy\\AppData\\Local\\XudDocker\\mainnet")

2020/12/07 15:01:38 unknown shorthand flag: 'n' in -n

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
```
and this error

**Comment by krrprr** [comment]
Many thanks for the feedback @JoPark20 :pray: 

> But now i have one question: why doesnt get the environment shutdown when closing the app?
> I know i am no experienced user, but at the moment it is quite difficult to shut it down completely (if you dont know it yet)

This was actually a design decision we made to move the app to tray (running in background) when the window gets closed. The reasoning for that is that the users would generally want the environment be up and running while they have open orders. Looks like in Windows it is not that obvious as the tray icon gets hidden behind the arrow. Have to see how that can be improved.

> Cant open XUD with shortcut when i didnt shutdown the environment (expected?); works fine after shutting down environment.

Would be reasonable if the window would get restored if the app is running in the background. https://github.com/ExchangeUnion/xud-ui/issues/140

> And create somehow automatically a shortcut that gets placed on eg desktop so users like me hit 3 times xud.setup.exe :D (but thats already being worked on afaik)

Did you by chance manually delete the desktop icon at some point (maybe with a previous version of xud-ui)? Otherwise the desktop icon should be added/replaced with reinstall.

**Comment by krrprr** [comment]
> ```
> [2020-12-07 15:01:38.860] [error] failed to stop containers. Error: Command failed: E:\Work\ExchangeUnion\xud-ui\public\assets\xud-launcher.exe -n mainnet down
> Error: unknown shorthand flag: 'n' in -n
> Usage:
>   xud-launcher down [flags]
> 
> Flags:
>   -h, --help   help for down
> 
> Global Flags:
>       --mainnet-dir string   Mainnet environment folder (default "C:\\Users\\yy\\AppData\\Local\\XudDocker\\mainnet")
> 
> 2020/12/07 15:01:38 unknown shorthand flag: 'n' in -n
> 
>     at ChildProcess.exithandler (child_process.js:312:12)
>     at ChildProcess.emit (events.js:310:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Socket.<anonymous> (internal/child_process.js:443:11)
>     at Socket.emit (events.js:310:20)
>     at Pipe.<anonymous> (net.js:672:12)
> ```
> 
> and this error

Looks like you're using some kind of xud-ui version that was created in the early stage of launcher (the `-n` flag was there in the beginning but was then removed) @reliveyy

**Comment by kilrau** [comment]
What are the fixes we'd want to do in the course of this issue? @krrprr

**Comment by kilrau** [comment]
Thank you again for opening this issue and guiding us through the points to be fixed @JoPark20 !

We fixed:
- black screen
- multiple app instances (clicking onto the .exe multiple times)
- handling of outdated containers

Even though this will only be available with the next release, I am closing here since this is issue is about much more than only the black screen by now and we can open single-purpose issues after the new release is out and we all had a chance to run and test it :v:
