### ISSUE TITLE
Update Feature Electron App

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#20]
Enable updating the application without manually downloading and installing a new version.

**Comment by kilrau** [comment]
Recap: idea is to use https://github.com/vercel/hazel for Win & Mac, for Linux just show the update notification with download button because there is [no standardized way to load updates yet.](https://github.com/vercel/hazel/issues/5)

**Comment by kilrau** [comment]
1. Display there is an update
2. Allow installing updates (pulling containers)

**Comment by krrprr** [comment]
> 2. Docker update: trigger accepting docker update prompt via api for local & remote environments: #88 

This actually only applies to remote environments. When the electron app is updated, the new launcher version comes with it (in case the new xud-ui version with the latest launcher is released, which should be the practice) and it defines the versions, so there is no need to update the local xud-docker environment separately.

**Comment by kilrau** [comment]
Right. Good.

How could an update of a remote environment work though if I am connecting to it via the Electron App / browser via the build-in web app of the proxy container?

**Comment by krrprr** [comment]
> Right. Good.
> 
> How could an update of a remote environment work though if I am connecting to it via the Electron App / browser via the build-in web app of the proxy container?

I think the exact implementation of remote environments should be discussed and/or decided in https://github.com/ExchangeUnion/xud-ui/issues/88.
The tricky part there is the case when the user connects to a remote environment via the xud-ui app - the versions have to be compatible. Have no plan for this yet.

**Comment by krrprr** [comment]
> Recap: idea is to use https://github.com/vercel/hazel for Win & Mac, for Linux just show the update notification with download button because there is [no standardized way to load updates yet.](https://github.com/vercel/hazel/issues/5)

Seems that https://www.electronjs.org/docs/tutorial/updates#using-updateelectronjsorg would be sufficient instead of hazel. In both ways the code-signing is required at least for macOS.

**Comment by kilrau** [comment]
> In both ways the code-signing is required at least for macOS.

I am taking care of an Apple developer account today.
