### ISSUE TITLE
Console view

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#29]
Pre-selection of all xucli commands

**Comment by kilrau** [comment]
See wireframe

**Comment by kilrau** [comment]
![image](https://user-images.githubusercontent.com/19181985/98843649-8d7f2800-244b-11eb-9313-1a02207ec2da.png)

**Comment by kilrau** [comment]
Rethinking this... now that the xud-ui-dashboard is running in the api container we actually could expose the real `xud ctl` / `xucli`, right? @krrprr

**Comment by raladev** [comment]
Agreed with real xucli using, but what about xud-docker commands (loglevel and others). Is it possible to use them too? If i understood correctly, these commands are part of utils, not xucli. @reliveyy

**Comment by kilrau** [comment]
That would be using the `xud ctl` as is. Can you add some details how this would work? @reliveyy

**Comment by reliveyy** [comment]
Yes. It's better to embed xud-ctl shell inside the explorer console page.  And the frontend could use websocket/socketio to exchange data of stdin/stdout/stderr. Here is a draft implementation details:

For our traditional command-line users:
1. Run xud.sh/xud.ps1
2. Run setup.sh/setup.ps1
3. Start proxy(api) container
4. Start xudctl shell with `eval $(curl -k -d "$@" -d "$(env)" https://localhost:8889/api/v1/xudctl-script)`

For our new GUI users:
1. Run XUD Explorer
2. Go to "Console" page
3. `POST https://localhost:8889/api/v1/xudctl` will return an execution ID (eid)
4. Connect to Socket.IO server `https://localhost:8889/socket.io`
5. Send input key stokes to Socket.IO event `input-eid`
6. Listen output from Socket.IO event `output-eid` (it will organize data like docker hijacked http response, aka one connection contains stdout & stderr)
