### ISSUE TITLE
MM Bot view

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#31]
This page gives an overview of Arby trades on OpenDEX, the related trades on the connected CEX and most importantly the generated profit each, as well as accumulated daily/weekly/monthly.

**Comment by peartobear** [comment]
Oh the setup screen named `MM Bot onboard` there is an active pair selection dropdown, it should only consist of the pairs available on `xucli lispairs` and then check against the hardcoded pair list client side so as to remove the risk of user selecting pair that shows up in `xucli listpairs` but isn't supported by the centralised exchange.
