### ISSUE TITLE
Add deposit and withdraw functionality

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#37]

**Comment by krrprr** [comment]
How do we want to handle the case the `timeout_block_height` is reached and the user hasn't navigated away from the deposit view? The options that come to my mind right now are:

1. automatically navigate back to the balance view;
2. automatically place a new deposit request;
3. add a warning message that the address is not valid anymore.

@kilrau  @raladev  @peartobear

**Comment by kilrau** [comment]
I think #2 provide the best UX.

**Comment by raladev** [comment]
1. I remember that boltz sometimes has a problems with deposits, so do we want to implement status page/status string for deposit status monitoring?
2. If `timeout_block_height` was reached after deposit, how we should notify user?
@kilrau @peartobear

**Comment by raladev** [comment]
> I think #2 provide the best UX.

then we also need alert that address was updated, because users can missed the update, but have old address in copy buffer.

**Comment by kilrau** [comment]
> I remember that boltz sometimes has a problems with deposits, so do we want to implement status page/status string for deposit status monitoring?

There should only be a problem if boltz is down/internet connection issues or ran out of funds - in that case we should throw a "Couldn't reach deposit service" error when navigating to the deposit page @krrprr 

I can't think of a good reason to display boltz in `status` or elsewhere @raladev . As a user I am only interested in boltz' status if I am depositing/withdrawing. So either things work when I navigate to these pages, or they don't and we throw an error (see above).

> If timeout_block_height was reached after deposit, how we should notify user?
> then we also need alert that address was updated

Same thing. And I agree to make the user aware: display the new address in case `timeout_block_height` was reached with an additional red (i) saying sth like  `Timeout reached, address changed!`

Wdyt? @raladev @krrprr @peartobear

**Comment by krrprr** [comment]
Good. I like the idea of requesting a new deposit address with a message that it was updated.

> in that case we should throw a "Couldn't reach deposit service" error when navigating to the deposit page

Yep, we should display some kind of error message anyway if something goes wrong. I suggest we'd show a general message like "Couldn't reach deposit service" and the message from the API response beneath it. That would indicate more precisely what went wrong.

**Comment by krrprr** [comment]
Regarding the current "wallets are in read-only mode" warning, we should either change it ("ethereum wallets are in read-only mode" or whatever is more understandable) or move it into each wallet section that does not have the deposit and withdraw buttons.
Any preferences regarding that @kilrau @peartobear @raladev ?

**Comment by kilrau** [comment]
I would say just remove it as part of https://github.com/ExchangeUnion/xud-ui/issues/37

**Comment by krrprr** [comment]
Follow-up issue to add the deposit and withdraw functionality via Connext https://github.com/ExchangeUnion/xud-ui/issues/113
