### ISSUE TITLE
Display a warning when setup of password, mnemonic, backup not completed

### ISSUE THREAD

**Issue by krrprr** [ExchangeUnion/xud-ui#39]
- When the initial backup has not been completed, an according warning message is displayed (see wireframe).
- The `Setup Now` button redirects to the settings view where the backup process can be done.
- When the user has not deposited any funds, the warning message can be closed.

The setup of password, mnemonic, and backup are implemented with https://github.com/ExchangeUnion/xud-ui/issues/141

**Comment by kilrau** [comment]
Depends on https://github.com/ExchangeUnion/xud/issues/1981 & https://github.com/ExchangeUnion/xud/issues/1982
