### ISSUE TITLE
Installation flow notes (Windows, v1.1.0-alpha.5)

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-ui#72]
The pathway was thorny and dangerous.

Notes for discussion:

General:
- [ ] need to add sum for each binary on release page for sumcheck and add instruction how to build binary (to verify published sum).
- [ ] set min size of the xud-explorer window

Main screen:
- [ ] No Back button on Connect page, to return on main screen I need to restart the app. 

Installation:
- [ ] it would be good to have `Hello` window when running v1.1.0-alpha.5 exe, that will describe what will be installed and where (with certain path) like all installers do, because I felt unwell when Ш got installation progress immediately after exe running.
- [ ] add progress string for docker download (good for slow internet);
- [ ] add progress bar for docker installation or maybe console output printing, like travis do it; installation screen says that it may take ~3 mins, my installation took ~10 mins.

Post-installation process:
- [ ] i did not notice `Reboot later` button at the end of the installation (maybe i just missed it). it would be good to have it. 
- [ ] wsl screen: add link to instruction how to disable wsl (first link contains info only about wsl patch installation).
- [ ] wsl screen: after wsl installation, windows reboot is required (even if u rebooted the PC before (after docker installation)). Would be good to mention it before displaying `Waiting for docker start` screen. (I spent ~15 mins in attempts to run docker after installation).
- [ ] wsl screen: integrate wsl installation/disabling into docker installation process with minimum user actions.

**Comment by kilrau** [comment]
> need to add sum for each binary on release page for sumcheck and add instruction how to build binary (to verify published sum)

https://github.com/ExchangeUnion/xud-ui/issues/80

>  set min size of the xud-explorer window

https://github.com/ExchangeUnion/xud-ui/issues/81

>  No Back button on Connect page, to return on main screen I need to restart the app.

https://github.com/ExchangeUnion/xud-ui/issues/82

>  it would be good to have Hello window when running v1.1.0-alpha.5 exe, that will describe what will be installed and where (with certain path) like all installers do, because I felt unwell when Ш got installation progress immediately after exe running.

https://github.com/ExchangeUnion/xud-ui/issues/83

>  add progress string for docker download (good for slow internet);

https://github.com/ExchangeUnion/xud-ui/issues/84

>  add progress bar for docker installation or maybe console output printing, like travis do it; installation screen says that it may take ~3 mins, my installation took ~10 mins.

https://github.com/ExchangeUnion/xud-ui/issues/85

>  i did not notice Reboot later button at the end of the installation (maybe i just missed it). it would be good to have it.

https://github.com/ExchangeUnion/xud-ui/issues/86

>  wsl screen: add link to instruction how to disable wsl (first link contains info only about wsl patch installation).
> wsl screen: after wsl installation, windows reboot is required (even if u rebooted the PC before (after docker installation)). Would be good to mention it before displaying Waiting for docker start screen. (I spent ~15 mins in attempts to run docker after installation).
> wsl screen: integrate wsl installation/disabling into docker installation process with minimum user actions.

https://github.com/ExchangeUnion/xud-ui/issues/87

**Comment by kilrau** [comment]
All points have separate issues, closing here.
