### ISSUE TITLE
Landing: "Start" instead of "Create" when env exists

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#90]
See wireframe

**Comment by JoPark20** [comment]
We could add something like below: 
![Screenshot (64)](https://user-images.githubusercontent.com/43677783/99686482-ea01c900-2a83-11eb-95f1-4296f92141da.png)
or
![Screenshot (61)](https://user-images.githubusercontent.com/43677783/99686523-f38b3100-2a83-11eb-862c-c610524091f8.png)

or "Welcome back to XUD" / "Welcome back to OpenDEx"

**Comment by kilrau** [comment]
Your suggestion is to mention/show `OpenDEX` in addition to `XUD`?

**Comment by JoPark20** [comment]
Yes, but just a thought / suggestion for start screen when the wallet has been set up already.
or a "welcome back" screen => user knows for sure he is using the set up wallet, not starting from the scratch again.

**Comment by erkarl** [comment]
This issue requires the binary launcher to be integrated since we'll need to verify the docker volume exists to detect existing environment.

Should we move this to 1.3.0?

**Comment by kilrau** [comment]
K, but we still want the binary launcher for 1.2.0
