### ISSUE TITLE
Suggestion for opening screen

### ISSUE THREAD

**Issue by JoPark20** [ExchangeUnion/xud-ui#95]
improvement suggestion: 
do not preselect an option, only show "create" and "connect" when opening the application; hide "next" meanwhile
![Screenshot (21)_LI](https://user-images.githubusercontent.com/43677783/98444701-6ce56400-2113-11eb-996d-b11cffcad4ff.jpg)
show "next" only when an option is chosen
![Screenshot (21)](https://user-images.githubusercontent.com/43677783/98444719-825a8e00-2113-11eb-8a9f-69415b3c6c47.png)

**Comment by KingJoKo** [comment]
But i know most users will set up their wallet the first time as this product is very new, so maybe my suggestion isnt really useful at this point ^^

**Comment by kilrau** [comment]
I like that! As of now I happen to re-click create and wonder why its not creating until I notice the next button. Your suggestion fixes that.

Lets do it! To be changed:
- default state is non-selected when opening lamding page
- once an option was selected, display create

Who is taking this one? @krrprr @erkarl

**Comment by krrprr** [comment]
Thanks a lot for the suggestion @JoPark20!
@kilrau implemented the changes you suggested, and that indeed seems like a better UX.
